CREATE TABLE IF NOT EXISTS `Configuration`.`Locations` (
	`LocationId` INT(11) NOT NULL,
	`LocationCode` VARCHAR(10) NOT NULL COLLATE 'utf8mb4_general_ci',
	`Depot` VARCHAR(50) NULL DEFAULT NULL,
	`Lat` DOUBLE NULL DEFAULT NULL,
	`Lon` DOUBLE NULL DEFAULT NULL,
	`Zipcode` VARCHAR(10) NULL DEFAULT NULL,
	`GISX` BIGINT(20) NULL DEFAULT NULL,
	`GISY` BIGINT(20) NULL DEFAULT NULL,
	`City` VARCHAR(50) NULL DEFAULT NULL,
	`Street` VARCHAR(50) NULL DEFAULT NULL,
	`Housenumber` VARCHAR(50) NULL DEFAULT NULL,
	`WarehouseReference` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`LocationId`)
);